#!/bin/bash

tput clear
clear


tput cup 3 19
tput setaf 3
echo "Enter System Password Below to Continue"
tput sgr0

wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome-stable_current_amd64.deb
rm google-chrome-stable_current_amd64.deb

